# -*- coding: utf-8 -*-
"""readRAW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XE-JnRCi9L6zSkoXGhe_7ICc_7lQlh0V
"""

import numpy as np
import cv2
def read_raw(file:str,shape:tuple,dtype):
    '''
    读取raw图
    :param file: 文件名
    :param shape: 读取的数据排列，(row,col,channel)
    :param dtype: raw文件类型
    :return: 读取的数据
    '''
    # 从raw文件中读取数据
    data = np.fromfile(file,dtype=dtype)
    # 将读取到的数据重新排列
    data = np.reshape(data,newshape=shape)
    # 返回数据
    return data

# raw_path = f"./Test Images/GrayImages/Lena.raw"
raw_path = f"./Lena_test.raw"
img = read_raw(raw_path,(512,512,1),dtype=np.uint8)
print(type(img))
print(np.shape(img))
cv2.imwrite(f"lena_test.jpg",img)


for QF in [80,5, 10, 20, 50,  90]:
  img = read_raw(f"./Lena_QF{QF}_decoded.raw",(512,512,1),dtype=np.uint8)
  print(type(img))
  print(np.shape(img))


  #dst = cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
  #print(np.shape(dst))
  #cv2.imwrite(f"{QF}.jpg",dst)
  cv2.imwrite(f"{QF}.jpg",img)